kafka:
  output_topic: "fraud_predictions"
  security_protocol: 'SASL_PLAINTEXT'
  sasl_mechanism: 'SCRAM-SHA-512'

kuberay:
  model:
    tune: false
    sample_fraction_for_tuning: 0.1 # Realiza un muestreo estratificado para acelerar el tuning
    target: "attack"
    num_classes: 6
    framework: "xgboost"
    seed: 42
    mlflow_tracking_uri: "http://mlflow.mlflow.svc.cluster.local:5000"
    mlflow_experiment_name: "kuberay-attack-detection"
    path: "../../models/fraud_detection_model.pkl"
    

spark:
  app_name: "spark-preprocessing"
  bucket: "k8s-mlops-platform-bucket" # dummy bucket name
  read_batch_size: 512  # Max MB read into memory per batch
  write_batch_size: 100000  # Max lines written to S3 per batch
  pipeline:
    module: "preprocessing.preprocessing_001"

