apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: kuberay-job
  namespace: ray
spec:
  entrypoint: python3 /home/ray/app/repo/k3s/kuberay/main.py

  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 100

  runtimeEnvYAML: |
    env_vars:
      # Final training (single run): fewer workers, more CPU per worker.
      # Recommended use NUM_WORKERS = NUM_NODES
      NUM_WORKERS: "2"
      # Recommended NUM_CPUS of the NODE minus 1 for system overhead.
      CPUS_PER_WORKER: "8"

      # Each trial (train) will use NUM_WORKERS_TUNE
      NUM_WORKERS_TUNE: "1"
      # Each trial (train) will use CPUS_PER_WORKER_TUNE
      CPUS_PER_WORKER_TUNE: "6"
      # The total number of CPUS will be NUM_WORKERS_TUNE * CPUS_PER_WORKER_TUNE
      # Number of CPUs to use for Ray Datasets during tuning for each worker.
      NUM_CPUS_DATA_TUNE: "2"
      # Maximum concurrent trials during tuning. 
      MAX_CONCURRENT_TRIALS: "2"

      # Hard caps to prevent per-trial pandas materializations from OOM'ing.
      # Tune loads Ray Datasets inside each trial.
      TUNE_MAX_TRAIN_ROWS: "250000"
      TUNE_MAX_VAL_ROWS: "150000"

      # TOTAL NUMBER OF CPUS in the RAY CLUSTER. I leave 1 CPU free for system overhead in each worker.
      NUM_CPUS_CLUSTER: "16"

      # Performance knobs (small datasets):
      RAY_MATERIALIZE_DATASETS: "1"
      RAY_MATERIALIZE_DATASETS_TUNE: "1"

  rayClusterSpec:
    rayVersion: "2.52.0"
    enableInTreeAutoscaling: false # true
    autoscalerOptions:
      version: v2
      upscalingMode: Default
      idleTimeoutSeconds: 60

    ########################
    # HEAD
    ########################
    headGroupSpec:
      rayStartParams:
        # Per Ray docs: setting num-cpus:"0" prevents scheduling CPU workloads on head.
        num-cpus: "0"
      template:
        spec:
          containers:
            - name: ray-head
              image: ray-cluster:2.52.0
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "2"
                  memory: "3Gi"
                requests:
                  cpu: "1"
                  memory: "3Gi"
              volumeMounts:
                - name: job-files
                  mountPath: /home/ray/app
              envFrom:
                - secretRef:
                    name: env-secret
              env:
                - name: RAY_enable_infeasible_task_early_exit
                  value: "true"
                - name: RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION
                  value: "0.7"
                - name: RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO
                  value: "0"

          initContainers:
            - name: git-sync
              image: registry.k8s.io/git-sync/git-sync:v4.1.0
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              env:
                - name: GITSYNC_REPO
                  value: "https://github.com/takenking9879/Kubernetes-MLOPS-platform"
                - name: GIT_SYNC_BRANCH
                  value: "main"
                - name: GIT_SYNC_ROOT
                  value: "/git"
                - name: GIT_SYNC_DEST
                  value: "repo"
                - name: GIT_SYNC_WAIT
                  value: "30"
                - name: GITSYNC_ONE_TIME
                  value: "true"
              volumeMounts:
                - name: job-files
                  mountPath: /git

          volumes:
            - name: job-files
              emptyDir: {}

    ########################
    # WORKERS
    ########################
    workerGroupSpecs:
      - replicas: 2
        minReplicas: 2
        maxReplicas: 2
        groupName: small-group
        rayStartParams: {}

        template:
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: ray.io/group
                            operator: In
                            values:
                              - small-group
                      topologyKey: kubernetes.io/hostname

            containers:
              - name: ray-worker
                image: ray-cluster:2.52.0
                resources:
                  limits:
                    # Laptop single-node "simulate 2 nodes": run 2 worker pods on the same host.
                    # Sized so both worker pods can be scheduled together.
                    cpu: "9"
                    memory: "5Gi"
                  requests:
                    cpu: "9"
                    memory: "5Gi"
                volumeMounts:
                  - name: job-files
                    mountPath: /home/ray/app
                envFrom:
                  - secretRef:
                      name: env-secret
                env:
                  - name: RAY_enable_infeasible_task_early_exit
                    value: "true"
                  - name: RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION
                    value: "0.7"
                  - name: RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO
                    value: "0"

            initContainers:
              - name: git-sync
                image: registry.k8s.io/git-sync/git-sync:v4.1.0
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 200m
                    memory: 256Mi
                env:
                  - name: GITSYNC_REPO
                    value: "https://github.com/takenking9879/Kubernetes-MLOPS-platform"
                  - name: GIT_SYNC_BRANCH
                    value: "main"
                  - name: GIT_SYNC_ROOT
                    value: "/git"
                  - name: GIT_SYNC_DEST
                    value: "repo"
                  - name: GIT_SYNC_WAIT
                    value: "30"
                  - name: GITSYNC_ONE_TIME
                    value: "true"
                volumeMounts:
                  - name: job-files
                    mountPath: /git

            volumes:
              - name: job-files
                emptyDir: {}
