apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: kafka
data:
  # UI binds to 8080
  UI_PORT: "8080"

---
# Secret expected: kafka-ui-secret in namespace kafka
# It should contain key: SASL_JAAS with value:
# org.apache.kafka.common.security.scram.ScramLoginModule required username="ml-platform" password="<PASSWORD>";
# Create it with:
# kubectl create secret generic kafka-ui-secret -n kafka --from-literal=SASL_JAAS='org.apache.kafka.common.security.scram.ScramLoginModule required username="ml-platform" password="<PASS>";'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "my-kafka-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: "my-kafka-cluster-kafka-bootstrap:9093" #192.168.65.3:31386 checar si es este o el otro 
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-secret
                  key: SASL_JAAS
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: ""
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
