apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic-traffic
  labels:
    strimzi.io/cluster: my-kafka-cluster
  namespace: kafka
spec:
  topicName: topic-traffic
  partitions: 6
  replicas: 1

---

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic-prediction
  labels:
    strimzi.io/cluster: my-kafka-cluster
  namespace: kafka
spec:
  topicName: topic-prediction
  partitions: 6
  replicas: 1
  config:
    retention.ms: 7200000
