apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: kafka
data:
  UI_PORT: "8083"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: ghcr.io/kafbat/kafka-ui:latest #provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            # --- App port (Spring Boot) ---
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-ui-config
                  key: UI_PORT

            # --- Kafka cluster ---
            - name: KAFKA_CLUSTERS_0_NAME
              value: "my-kafka-cluster"

            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: "my-kafka-cluster-kafka-bootstrap:9093"

            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_SSL"

            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: "SCRAM-SHA-512"

            # --- Credentials from Secret ---
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: KAFKA_USERNAME

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: KAFKA_PASSWORD

            # --- JAAS built dynamically ---
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              value: >
                org.apache.kafka.common.security.scram.ScramLoginModule required
                username="${KAFKA_USERNAME}"
                password="${KAFKA_PASSWORD}";

            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: ""

            # --- Trust Strimzi cluster CA (TLS listener on 9093) ---
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE
              value: "PEM"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION
              value: "/etc/kafka/ca/ca.crt"

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

          volumeMounts:
            - name: kafka-cluster-ca
              mountPath: /etc/kafka/ca
              readOnly: true

      volumes:
        - name: kafka-cluster-ca
          secret:
            secretName: my-kafka-cluster-cluster-ca-cert

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-ui
  ports:
    - port: 8083
      targetPort: 8083
